### ISSUE TITLE
Unknown layer:layers

### ISSUE THREAD

**Issue by gmt710** [BIGBALLON/cifar-10-cnn#11]
keras.models.load_model('vgg19_cifar10.h5')
but have an error:
D:\Users\Python\python3.exe D:/pythonwork/Adversarial/Cifar10_keras_Adversarial/MisClassification.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "D:/pythonwork/Adversarial/Cifar10_keras_Adversarial/MisClassification.py", line 100, in <module>
    main()
  File "D:/pythonwork/Adversarial/Cifar10_keras_Adversarial/MisClassification.py", line 21, in main
    kmodel = load_model(weight_path)
  File "D:\Users\Python\lib\site-packages\keras\engine\saving.py", line 261, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "D:\Users\Python\lib\site-packages\keras\engine\saving.py", line 335, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "D:\Users\Python\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "D:\Users\Python\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "D:\Users\Python\lib\site-packages\keras\engine\sequential.py", line 292, in from_config
    custom_objects=custom_objects)
  File "D:\Users\Python\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "D:\Users\Python\lib\site-packages\keras\utils\generic_utils.py", line 165, in deserialize_keras_object
    ':' + function_name)
ValueError: Unknown layer:layers

**Comment by gmt710** [comment]
LeNet_keras.py and Vgg19_keras.py generate the model.I loaded the model,and this error occurred.

**Comment by BIGBALLON** [comment]
Hi, @gmt710 

Please check your keras version. 
It works fine in my machine when I use the load_model().

maybe check these issues, [394](https://github.com/fizyr/keras-retinanet/issues/394)
[7585](https://github.com/keras-team/keras/issues/7585)
[10377](https://github.com/keras-team/keras/issues/10377)

**Comment by gmt710** [comment]
@BIGBALLON   what's your keras version？

**Comment by BIGBALLON** [comment]
@gmt710  **keras 2.1.5** with **tensorflow 1.4.1**

**Comment by gmt710** [comment]
@BIGBALLON   Thanks a lot. I solved this problem by updating the keras version to 2.2.4.The previous version was 2.2.0.

**Comment by BIGBALLON** [comment]
@gmt710  very glad to hear this news. 😄
